config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :therapists  do
    resources :appointments
  end
  resources :patients do
    resources :appointments
  end
  resources :notes
  

  root 'sessions#home'
  
  get '/signup', to: 'therapists#new'
  post '/signup', to: 'therapists#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  # resources :notes
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :therapist
  belongs_to :patient

  accepts_nested_attributes_for :patient
  # validates :date, presence: true
  # validates :time, presence: true
  # validates :appointment_type, presence: true

  # def patient_attributes=(attr)
  #   if attr[:name] != "" && attr[:injury_location]
  # end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient

  # validates :content, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :therapists, through: :appointments
    has_many :notes

    # validates :name, presence: true

end

app/models/therapist.rb
class Therapist < ApplicationRecord
    has_secure_password

    has_many :appointments
    has_many :patients, through: :appointments

    accepts_nested_attributes_for :appointments

    def self.create_from_omniauth(auth)
        therapist = Therapist.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |t|
            t.first_name = auth[:info][:first_name]
            t.last_name = auth[:info][:last_name]
            t.email = auth[:info][:email]
            t.password = SecureRandom.hex(17)
        end
    end
    
    def upcoming_appointments
        appointments.order(date: :desc).select { |a| a.date > (Date.now) }
    end

    # validates :first_name, presence: true
    # validates :last_name, presence: true
    # validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private
        def current_user
            @therapist ||= Therapist.find_by(id: session[:therapist_id]) if session[:therapist_id]
        end

        def logged_in?
            !!current_user
        end
    
        def redirect_if_not_logged_in
            redirect_to '/' if !logged_in? 
        end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        # @appointments = current_user.appointments.select {|a| a.persisted?}
        # @appointment = current_user.appointments.build
        @appointment = Appointment.new
    end

    def create
        @appointment = Appointment.new(appointment_params)
        # @appointment = current_user.appointments.build(appointment_params)
        # byebug
        if @appointment.save
            flash[:message] = "Appointment booked! See you then!"
            redirect_to therapist_appointments_path(@appointment.therapist_id, @appointment.id)
        else
            flash[:message] = "Appointment was not saved, please try again!"
            redirect_to new_therapist_path(@appointment.therapist_id, @appointment.id)
        end
    end
    
    def show
    end

    def update
        if @appointment.update(appointment_params)
            redirect_to appointments_path
        else
            flash[:message] = "Appointment was not updated, please try again!"
            render :edit
        end
    end

    def destroy
        @appointment.destroy
        redirect_to appointments_path
    end
 

    private

    def appointment_params
        params.require(:appointment).permit(:date, :time, :appointment_type, :therapist_id, :patient_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.new(patient_params)
        if @patient.save
            flash[:message] = "Patient successfully created!"
            redirect_to patients_path
        else 
            flash[:message] = "Patient was not created, please try again!"
            redirect_to new_patient_path
        end
    end

    private

    def patient_params
        params.require(:patient).permit(:name, :injury_location)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def home
    end

    def new
    end

    def omniauth
        therapist = Therapist.create_from_omniauth(auth)
        if therapist.valid?
            therapist.save
            session[:therapist_id] = therapist.id
            redirect_to therapist_path(therapist.id)
        else
            flash[:message] = therapist.errors.full_message
            redirect_to root_path
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    def create
        therapist = Therapist.find_by(email: params[:therapist][:email])
        if therapist && therapist.authenticate(params[:therapist][:password])
            session[:therapist_id] = therapist.id
            redirect_to therapist_path(therapist)
        else
            flash[:message] = "Invalid credentials. Please try again."
            redirect_to "/login"
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/therapists_controller.rb
class TherapistsController < ApplicationController

    def new
        @therapist = Therapist.new
    end
    
    def create
        @therapist = Therapist.new(therapist_params)
        if @therapist.save
            flash[:message] = "Successful signup. Welcome!"
            session[:therapist_id] = @therapist.id
            redirect_to @therapist
        else
            flash[:message] = "Unsuccessful signup! Please try again!"
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @therapist = Therapist.find_by_id(params[:id])
        redirect_to '/' if !@therapist
    end

    private

    def therapist_params
        params.require(:therapist).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/views/appointments/index.html.erb
<u><h1>All Appointments:</h1></u>

<% if @therapist.appointments.empty? %>
    <h4>No appointments scheduled at this time!</h4>
<% else %>
    <% @therapist.appointments.each do |appt| %>
        -<a href="/therapist/#{@therapist.id}/appointments" %= appt.date %><%= appt.time %><%= appt.appointment_type %> </a><br>
    <% end %>
<% end %>

app/views/appointments/new.html.erb
<h1>Create an Appointment!!</h1>

<p style="color: red;">
 <%= flash[:message] if flash[:message] %>
</p>

<%= form_for(@appointment) do |f| %>
    <%= f.hidden_field :therapist_id %>
    <%= f.label :date %>
    <%= f.date_field  :date %><br><br>

    <%= f.label :time %>
    <%= f.time_field  :time %><br><br>

    <%= f.label :appointment_type %>
    <%= f.select :appointment_type, ['Initial Evaluation', 'Follow Up'] %><br><br>

    <h2>Add a patient</h2>
  
   <%= f.fields_for :patients do |p| %>
        <%= p.label :name %>
        <%= p.text_field :name %><br><br>

        <%= p.label :injury_location %>
        <%= p.select :injury_location, ['Cervical Spine', 'Thoracic Spine' , 'Shoulder' , 'Elbow' , 'Hand' , 'Lumbar Spine' , 'Hip' , 'Knee' , 'Ankle/Foot'] %>
    <% end %><br><br>

    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Physical Therapy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center><u><h1>Rails Physical Therapy</h1></u></center>
    <div>
      <% if logged_in? %>
        <%= link_to "Home", therapist_path(id: @therapist.id) %> /
        <%= link_to "Create an appointment", new_therapist_appointment_path(@therapist.id) %> /
        <%= link_to "All appointments", appointments_path %> /
        <%= link_to "Create a patient", new_patient_path %> /
        <%= link_to "Logout", logout_path, method: "delete" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/therapists/new.html.erb
<h1>Sign Up</h1>

<p style="color: red;">
    <%= flash[:message] if flash[:message] %>
</p>

<%= form_for(@therapist) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br><br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br><br>

    <%= f.label :email %>
    <%= f.email_field :email %><br><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br><br>

    <%= f.submit "Signup" %>
<% end %>

<h3>Already have an account? Please <%= link_to "Login.", login_path %></h3>

app/views/therapists/show.html.erb
<h1>Welcome <%= @therapist.first_name + " " + @therapist.last_name %>!!!</h1>


<% if @therapist.appointments.empty? %>
    <h4>You currently don't have any appointments scheduled!</h4>
<% else %>
    <% @therapist.appointments.each do |appt| %>
        -<a href="/therapist/#{@therapist.id}/appointments"> <%= appt.date %><%= appt.time %><%= appt.appointment_type %> </a><br>
    <% end %>
<% end %>